name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for posting your first issue to this repo!"
          pr-message: "Thank you for submitting your first pull request!"
